name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: adamrehn/ue4-runtime:latest
    steps:
      - name: Install git 
        run: apt-get install git -y
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'
          architecture: 'x64'
      - name: Dependency 
        run: pip install -r requirements.txt
      - name: build 
        run: python packager.py
