name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull UE4 source
      run: git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/EpicGames/UnrealEngine.git
      - name: Setup
        run: |
          cd UnrealEngine
          ./Setup.sh
          ./GenerateProjectFiles.sh
      - name: Make
        run: make
      - name: CD back
        run: cd ..
      - uses: actions/setup-python@v2
        with:
          python-version: 'pypy3'
          architecture: 'x64'
      - name: Dependency 
        run: pip install -r requirements.txt
      - name: build 
        run: python packager.py
